x-logging:
    &default-logging
    driver: "json-file"
    options:
        max-size: "10m"
        max-file: "3"

services:
   dnsmasq:
      image: tgiesela/dnsmasq:latest
      build: .
      hostname: dnsmasq
      networks:
        mailnet:
          ipv4_address: ${DNSIP}
      container_name: dnsmasq
      ports: 
        - 53:53/udp
        - 53:53/tcp
      cap_add:
         - NET_ADMIN
      logging: *default-logging
      depends_on: [vpn]
      volumes:
        - ./dnsmasq.conf:/etc/dnsmasq.conf
      labels:
        - "com.tgiesela.vpn.hiddenip=true"
        - "com.tgiesela.vpn.accessible=true"
        - "com.tgiesela.vpn.containerport=53/tcp;53/udp"
        - "com.tgiesela.vpn.vpnport=53/tcp;53/udp"
